site_name: Home Lab Documentation
site_url: http://network-docs.shadmanhabib.com
repo_url: https://github.com/shadmanhabib/network-docs
repo_name: shadmanhabib/network-docs

theme: 
  name: material
  features:
    - navigation.instant
    - naviagtion.instant.prefetch
    - navigation.sections
    - navigation.indexes
    #- navigation.expand
    #- navigation.tabs
    #- toc.follow
    #- toc.integrate
    - navigation.path
    - search.suggest

nav:
  - 'index.md'
  - 1. Overview:
    - '01-overview/index.md'
    - Network Architecture: '01-overview/network-architecture.md'
  - 2. Raspberry Pi Servers:
    - '02-raspi-servers/index.md'
    - Home Assistant: '02-raspi-servers/homeassistant.md'
    - Network Pi: '02-raspi-servers/network-pi.md'
    - Backup Pi: '02-raspi-servers/backup-pi.md'
  - 3. Ubuntu Server: 
    - '03-ubuntu-server/index.md'
    - Data and Storage: '03-ubuntu-server/data.md'
  - 4. Docker:
    - '04-containers/index.md'
    - Portainter: '04-containers/portainer.md'
    - Primary Services:
      - Frigate: '04-containers/motioneye.md'
      - Jellyfin: '04-containers/jellyfin.md'
      - Actual: '04-containers/actual-budget.md'
    - Notes and File Management:
      - Syncthing: '04-containers/syncthing.md'
      - Outline: '04-containers/outline-wiki.md'
      - Paperless-ngx: '04-containers/paperless-ngx.md'
    - Media Processing:
      - MakeMKV: '04-containers/makemkv.md'
      - Handbrake: '04-containers/handbrake.md'
    - Network:
      - Homer: '04-containers/homer.md'
      - Pi-hole: '04-containers/pi-hole.md'
      - Tailscale: '04-containers/tailscale.md'
    - Authentication and Proxy:
      - Authelia: '04-containers/authelia.md'
      - LLDAP: '04-containers/lldap.md'
      - Nginx Proxy Manager: '04-containers/npm.md'